### ISSUE TITLE
v6.5 vs v6.6

### ISSUE THREAD

**Issue by cjrodriguez98** [bnediction/bonesis#7]
Hey! 

I am having very different performance when applying the marker reprogramming method to a BN. 

In version 6.5 I am able to compute the reprogramming markers of a big boolean network in a few minutes. While in v6.6 its been days and the program does not finish. I see that in v6,6 something changed. 
Can I trust my results with v6.5?

Thanks in advance

**Comment by cjrodriguez98** [comment]
Hello again! 

After a little more testing I am finding the version difference might not be the culprit. 
Could the issue be on an OS level?
On windows I am able to finish the computation in a 40 minutes. But on Linux the same script does not finish after 72 hours

**Comment by pauleve** [comment]
Hi, 
It could be due to a different version of clingo. Can you check the output of `clingo --version` on both setups?

**Comment by cjrodriguez98** [comment]
Hey Loïc, 

I checked and have the same version in both setups. I think I foud the issue. In windows I was filtering some components of the network incorrectly. 
With the correct filtering I have a bn of arround 12,000 components. That might be too large?

**Comment by pauleve** [comment]
For sure, that's large, but there could be hope.
Which function/command line do you use for the reprogramming?
You can try with setting environment variable CLINGO_OPTS="--sign-def=pos --vsids-acids" which sometimes helps..
We also have an internal improvement of the algorithm that may be more tractable. If you don't mind sharing your model and reprogramming setting, I can give a try here (you can share it by email at loic.pauleve@labri.fr).

**Comment by cjrodriguez98** [comment]
I am using it directly from python. Could I pass that paramater as opts in bonesis?

Let me prepare the data and I will for sure send you everything. 

Many thanks!
